from pydantic import BaseModel, Field, HttpUrl


class ProblemDetailsV1(BaseModel):
    """
    A model for representing problem details for HTTP APIs.

    Defined in RFC 7807: https://tools.ietf.org/html/rfc7807

    Attributes:
        title (str): A short, human-readable summary of the problem type. It
        SHOULD NOT change from occurrence to occurrence of the problem, except
        for purposes of localization (e.g., using proactive content negotiation;
        see
        [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.4),
        Section 3.4).

        detail (str): A human-readable explanation specific to this occurrence.

        status (int, optional): The HTTP status code
        ([RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-6),
        Section 6) generated by the origin server for this occurrence of the
        problem.

        type (HttpUrl, optional): A URI reference
        [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) that identifies
        the problem type. This specification encourages that, when dereferenced,
        it provide human-readable documentation for the problem type (e.g.,
        using HTML
        [W3C.REC-html5-20141028]
        (https://datatracker.ietf.org/doc/html/rfc7807#ref-W3C.REC-html5-20141028)).
        When this member is not present, its value is assumed to be
        "about:blank".

        instance (HttpUrl, optional): A URI reference that identifies the
        specific occurrence of the problem. It may or may not yield further
        information if dereferenced.
    """

    title: str = Field(
        default=...,
        alias="title",
        description="A short, human-readable summary of the problem type. "
        "It SHOULD NOT change from occurrence to occurrence of the problem, "
        "except for purposes of localization "
        "(e.g., using proactive content negotiation; "
        "see [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.4), "
        "Section 3.4).",  # noqa: E501
        min_length=1,
        max_length=255,
        pattern=r"^\S(.*\S)?$",
    )
    detail: str = Field(
        default=...,
        alias="detail",
        description="A human-readable explanation specific to this occurrence.",
        min_length=1,
        max_length=512,
        pattern=r"^\S(.*\S)?$",
    )
    status: int | None = Field(
        default=None,
        alias="status",
        ge=100,
        le=999,
        description="The HTTP status code "
        "([RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-6), "
        "Section 6) "
        "generated by the origin server for this occurrence of the problem.",
    )
    type: HttpUrl | None = Field(
        default=None,
        alias="type",
        description="A URI reference [RFC3986](https://datatracker.ietf.org/doc/html/rfc3986) "
        "that identifies the problem type. This specification encourages that, "
        "when dereferenced, it provide human-readable documentation for the problem "
        "type (e.g., using HTML "
        "[W3C.REC-html5-20141028](https://datatracker.ietf.org/doc/html/"
        "rfc7807#ref-W3C.REC-html5-20141028)). "
        'When this member is not present, its value is assumed to be "about:blank".',
    )
    instance: HttpUrl | None = Field(
        default=None,
        alias="instance",
        description="A URI reference that identifies the specific occurrence of the problem. "
        "It may or may not yield further information if dereferenced.",
    )
